/**
 * Claude Code adapter - generates CLAUDE.md format
 */

import { getCategoryInfo } from '../loader.js';

export const name = 'Claude Code';
export const outputPath = 'CLAUDE.md';
export const description = 'Generates CLAUDE.md for Claude Code';

/**
 * Check if an existing CLAUDE.md has a security section
 */
const SECTION_START = '<!-- js-secure-coding:start -->';
const SECTION_END = '<!-- js-secure-coding:end -->';

export function format(templates, options = {}) {
  const { framework = 'vanilla' } = options;
  const lines = [];

  lines.push(SECTION_START);
  lines.push('<!-- version: 2.0.0 -->');
  lines.push('');
  lines.push('# Security Rules (OWASP 2025)');
  lines.push('');
  lines.push(`> Auto-generated by js-secure-coding v2.0 | Framework: ${framework}`);
  lines.push('> Reference: https://owasp.org/Top10/2025/');
  lines.push('');

  for (const [category, content] of templates) {
    const info = getCategoryInfo(category);
    lines.push(`## ${info.owasp}: ${info.title}`);
    lines.push('');
    // Extract just the Rules and Quick Checklist sections for conciseness
    lines.push(extractEssentials(content));
    lines.push('');
  }

  lines.push(SECTION_END);

  return lines.join('\n');
}

/**
 * Merge security rules into existing CLAUDE.md content
 */
export function merge(existingContent, newSection) {
  if (existingContent.includes(SECTION_START)) {
    // Replace existing section
    const before = existingContent.substring(
      0,
      existingContent.indexOf(SECTION_START)
    );
    const after = existingContent.substring(
      existingContent.indexOf(SECTION_END) + SECTION_END.length
    );
    return before.trimEnd() + '\n\n' + newSection + '\n' + after.trimStart();
  }
  // Append to end
  const trimmed = existingContent.trimEnd();
  return (trimmed ? trimmed + '\n\n' : '') + newSection + '\n';
}

function extractEssentials(content) {
  const lines = content.split('\n');
  const result = [];
  let inRules = false;
  let inChecklist = false;

  for (const line of lines) {
    if (line.startsWith('## Rules') || line.startsWith('## Quick Checklist')) {
      inRules = line.startsWith('## Rules');
      inChecklist = line.startsWith('## Quick Checklist');
      result.push(line);
      continue;
    }
    if (line.startsWith('## ') && (inRules || inChecklist)) {
      inRules = false;
      inChecklist = false;
      continue;
    }
    if (inRules || inChecklist) {
      result.push(line);
    }
  }

  return result.join('\n').trim();
}
