/**
 * GitHub Copilot adapter - generates .github/copilot-instructions.md
 */

import { getCategoryInfo } from '../loader.js';

export const name = 'GitHub Copilot';
export const outputPath = '.github/copilot-instructions.md';
export const rulesDir = '.github/instructions';
export const description = 'Generates .github/copilot-instructions.md';

const SECTION_START = '<!-- js-secure-coding:start -->';
const SECTION_END = '<!-- js-secure-coding:end -->';

export function format(templates, options = {}) {
  const { framework = 'vanilla', version = '2.0.0' } = options;
  const lines = [];

  lines.push(SECTION_START);
  lines.push(`<!-- version: ${version} -->`);
  lines.push('');
  lines.push('## Security Coding Guidelines (OWASP 2025)');
  lines.push('');
  lines.push(
    'When writing or reviewing JavaScript/TypeScript code, follow these security rules:'
  );
  lines.push('');

  for (const [category, content] of templates) {
    const info = getCategoryInfo(category);
    // Copilot instructions should be concise - extract rules only
    lines.push(`### ${info.owasp}: ${info.title}`);
    lines.push('');
    lines.push(extractRulesOnly(content));
    lines.push('');
  }

  lines.push(SECTION_END);

  return lines.join('\n');
}

export function merge(existingContent, newSection) {
  if (existingContent.includes(SECTION_START)) {
    const before = existingContent.substring(
      0,
      existingContent.indexOf(SECTION_START)
    );
    const after = existingContent.substring(
      existingContent.indexOf(SECTION_END) + SECTION_END.length
    );
    return before.trimEnd() + '\n\n' + newSection + '\n' + after.trimStart();
  }
  const trimmed = existingContent.trimEnd();
  return (trimmed ? trimmed + '\n\n' : '') + newSection + '\n';
}

/**
 * Format templates into individual files for directory mode
 * Returns Map<filename, content>
 */
export function formatMultiple(templates, options = {}) {
  const files = new Map();
  for (const [category, content] of templates) {
    const info = getCategoryInfo(category);
    const lines = [
      `# ${info.owasp}: ${info.title}`,
      '',
      `> OWASP 2025 Security Rule | Generated by secure-coding-rules`,
      '',
      content.replace(/^# .+\n+(?:>.*\n+)*/, ''),
    ];
    files.set(`security-${category}.md`, lines.join('\n'));
  }
  return files;
}

/**
 * Generate reference text for copilot-instructions.md pointing to rules directory
 */
export function formatReference(categories, options = {}) {
  const { version = '2.0.0' } = options;
  const lines = [
    SECTION_START,
    `<!-- version: ${version} -->`,
    '',
    '## Security Coding Guidelines (OWASP 2025)',
    '',
    'Detailed security rules are in `.github/instructions/security-*.md`.',
    '',
  ];
  for (const cat of categories) {
    const info = getCategoryInfo(cat);
    lines.push(`- \`security-${cat}.md\` - ${info.owasp}: ${info.title}`);
  }
  lines.push('');
  lines.push(SECTION_END);
  return lines.join('\n');
}

function extractRulesOnly(content) {
  const lines = content.split('\n');
  const result = [];
  let inRules = false;

  for (const line of lines) {
    if (line.startsWith('## Rules')) {
      inRules = true;
      continue;
    }
    if (line.startsWith('## ') && inRules) {
      inRules = false;
      continue;
    }
    if (inRules) {
      // Convert ### to bullet points for Copilot's flatter format
      if (line.startsWith('### ')) {
        result.push(`- **${line.replace('### ', '').replace(/^\d+\.\s*/, '')}**`);
      } else if (line.startsWith('- **DO') || line.startsWith('- **DON\'T') || line.startsWith('- **WHY')) {
        result.push(`  ${line}`);
      }
    }
  }

  return result.join('\n').trim();
}
