/**
 * Windsurf adapter - generates .windsurf/rules/*.md format
 */

import { getCategoryInfo } from '../loader.js';

export const name = 'Windsurf';
export const outputDir = '.windsurf/rules';
export const description = 'Generates .windsurf/rules/*.md files';

/**
 * Format templates into individual .md files for Windsurf
 * Returns Map<filename, content>
 */
export function formatMultiple(templates, options = {}) {
  const files = new Map();

  for (const [category, content] of templates) {
    const info = getCategoryInfo(category);
    const filename = `security-${category}.md`;
    const formatted = formatWindsurfRule(category, content, info, options);
    files.set(filename, formatted);
  }

  return files;
}

function formatWindsurfRule(category, content, info, options = {}) {
  const { framework = 'vanilla' } = options;
  const lines = [];

  lines.push(`# ${info.owasp}: ${info.title}`);
  lines.push('');
  lines.push(`> OWASP 2025 Security Rule | Framework: ${framework}`);
  lines.push('> Generated by js-secure-coding');
  lines.push('');
  lines.push(stripTitle(content));

  return lines.join('\n');
}

function stripTitle(content) {
  const lines = content.split('\n');
  // Remove the first H1 title if present (we add our own)
  if (lines[0]?.startsWith('# ')) {
    lines.shift();
    // Remove blank line after title
    if (lines[0]?.trim() === '') lines.shift();
    // Remove blockquote lines after title (e.g., > description)
    while (lines[0]?.startsWith('>')) {
      lines.shift();
    }
    // Remove blank line after blockquote
    if (lines[0]?.trim() === '') lines.shift();
  }
  return lines.join('\n');
}
